import Head from 'next/head'
import Image from 'next/image'
import BuildBetterProducts from '../components/BuildBetterProducts'
import Header from '../components/Header'
import SimplifyHowTeamWorks from '../components/SimplifyHowTeamWorks'
import UpsellManage from '../components/UpsellManage'
import Footer from '../components/Footer';
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='px-6 pt-10 lg:px-40 lg:pt-14'>
        <Header/>
        <main>
          <BuildBetterProducts/>
          <UpsellManage/>
        </main>
      </div>
      <SimplifyHowTeamWorks/>
      <Footer/>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
