import Head from 'next/head'
import Image from 'next/image'
import BuildBetterProducts from '../components/BuildBetterProducts'
import Header from '../components/Header'
import SimplifyHowTeamWorks from '../components/SimplifyHowTeamWorks'
import UpsellManage from '../components/UpsellManage'
import Footer from '../components/Footer';
import Testimonials from '../components/Testimonials'

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Frontend Mentor | Manage landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png"></link>
      </Head>
      {/* background images */}
      <div className='absolute w-[33.75rem] h-[26.875rem] -top-[5.625rem] -right-[12.875rem] lg:-top-[13.75rem] lg:-right-[17.5rem] lg:w-[62.5rem] lg:h-[53.125rem] -z-50'>
          <Image fill src="/images/bg-simplify-section.svg" alt="background image"/>
      </div>
      <div className='absolute w-[26.25rem] h-[21.25rem] top-[28.75rem] -right-[18.125rem] lg:top-[65.625rem] lg:-left-[36.25rem] lg:w-[62.5rem] lg:h-[56.25rem] -z-50'>
          <Image fill src="/images/bg-simplify-section.svg" alt="background image"/>
      </div>

      <div className='px-6 pt-10 md:px-20 lg:px-10 xl:px-40 xl:pt-14'>
        <Header/>
        <main>
          <BuildBetterProducts/>
          <UpsellManage/>
          <Testimonials/>
        </main>
      </div>
      <SimplifyHowTeamWorks/>
      <Footer/>
    </div>
  )
}
